name: Test
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "latest"
      - name: Setup Node.js@lts environment
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.cache/pnpm
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('package.json') }}
      - run: pnpm i --fix-lockfile
      - run: pnpm run lint
      - run: pnpm run build
      - run: pnpm run test:e2e
